---

- hosts: all
  become: true
  tasks:


  - name: update repo index
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: apache2
      state: absent

  - name: add php support
    apt:
      name: libapache2-mod-php
      state: absent
