---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (AlmaLinux)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false  
    when: ansible_distribution == "AlmaLinux" 

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"  

- hosts: all
  become: true
  roles:
    - base
    
- hosts: all
  become: true
  roles:
    - workstations

- hosts: all
  become: true
  roles:
    - web_servers
    
- hosts: all
  become: true
  roles:
    - db_servers

- hosts: all
  become: true
  roles:
    - file_servers
    
- hosts: all
  become: true
  roles:
    - name_servers


