---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (AlmaLinux)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false  
    when: ansible_distribution == "AlmaLinux" 

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"  


- hosts: web_servers
  become: true 
  tasks: 


  - name: install apache and php packages for Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php packages for AlmaLinux
    tags: apache,AlmaLinux,httpd
    dnf: 
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "AlmaLinux"

- hosts: db_servers
  become: true 
  tasks: 


  - name: install mariadb package CentOS
    tags: centos,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "AlmaLinux"

  - name: install mariadb package Ubuntu
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true 
  tasks: 

  - name: install samba package 
    tags: samba
    package:
      name: samba
      state: latest