- name: install BIND9
  package:
    name:
      - bind9
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install BIND9
  package:
    name:
      - bind
    state: latest
  when: ansible_distribution == "AlmaLinux"